kind: pipeline
type: kubernetes
name: 11111111111

steps:
  - name: step111111
    image: busybox
    commands:
      - echo "step1"
      - echo ${DRONE_TAG}
      - echo ${DRONE_BUILD_STATUS}
      - cat /run/drone/env

  - name: step2222222
    image: busybox
    commands:
      - echo "step2"
      - echo ${DRONE_TAG}
      - echo ${DRONE_BUILD_STATUS}
      - cat /run/drone/env
